### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ghost** [mbear/quickstart-archetypes#1]
wx\mp\aes\Sample.java:[1,0] 错误: 非法字符: \65279
wx\mp\aes\Sample.java:[1,9] 错误: 需要class, interface或enum
wx\mp\aes\AesException.java:[1,0] 错误: 非法字符: \65279
wx\mp\aes\AesException.java:[1,9] 错误: 需要class, interface或enum

**Comment by mbear** [comment]
详见微信企业版开发官网说明 http://qydev.weixin.qq.com/wiki/index.php?title=%E5%8A%A0%E8%A7%A3%E5%AF%86%E5%BA%93%E4%B8%8B%E8%BD%BD%E4%B8%8E%E8%BF%94%E5%9B%9E%E7%A0%81，有两个jar包需要拷贝到jvm。
